---
# tasks file for hostname
  - name: Coletando fatos
    set_fact:
      nome: "{{ ansible_default_ipv4.address }}"
    register: address_result     

  - name: gravando saída
    set_stats:
      data: 
        resultado_nome: "{{ address_result }}"