---
# tasks file for hostname
  - name: Coletando fatos
    set_fact:
      address: "{{ ansible_default_ipv4.address }}"
    register: address_result

  - name: gravando saída
    set_stats:
      data: 
        resultado_address: "{{ address_result.ansible_facts.address }}"